////////////////////////////////////////////////////////////////////////////////
//
//  YOUR QUILL
//
////////////////////////////////////////////////////////////////////////////////

#include "html_common.hpp"
#include <yq/log/Logging.hpp>
#include <yq/stream/Ops.hpp>
#include <yq/web/WebContext.hpp>
#include <yq/web/WebHtml.hpp>

#include "atom/html.hpp"
#include "category/html.hpp"
#include "class/html.hpp"
#include "directory/html.hpp"
#include "document/html.hpp"
#include "field/html.hpp"
#include "folder/html.hpp"
#include "form_html.hpp"
#include "fragment/html.hpp"
#include "image/html.hpp"
#include "leaf/html.hpp"
#include "meta_object/html.hpp"
#include "meta_property/html.hpp"
#include "meta_type/html.hpp"
#include "web/html.hpp"
#include "root/html.hpp"
#include "tag/html.hpp"
#include "thumbnail/html.hpp"
#include "user/html.hpp"

#include "atom/struct.hpp"
#include "category/struct.hpp"
#include "class/struct.hpp"
#include "directory/struct.hpp"
#include "document/struct.hpp"
#include "field/struct.hpp"
#include "folder/struct.hpp"
#include "fragment/struct.hpp"
#include "image/struct.hpp"
#include "leaf/struct.hpp"
#include "root/struct.hpp"
#include "tag/struct.hpp"
#include "user/struct.hpp"

//#include "category/cdb.hpp"
#include "directory/cdb.hpp"
#include "document/cdb.hpp"
#include "folder/cdb.hpp"
#include "fragment/cdb.hpp"
#include "image/cdb.hpp"
#include "root/cdb.hpp"
#include "tag/cdb.hpp"
#include "user/cdb.hpp"

#include "atom/html.ipp"
#include "category/html.ipp"
#include "class/html.ipp"
#include "field/html.ipp"
#include "directory/html.ipp"
#include "document/html.ipp"
#include "field/html.ipp"
#include "folder/html.ipp"
#include "form_html.ipp"
#include "fragment/html.ipp"
#include "image/html.ipp"
#include "leaf/html.ipp"
#include "meta_object/html.ipp"
#include "meta_property/html.ipp"
#include "meta_type/html.ipp"
#include "web/html.ipp"
#include "root/html.ipp"
#include "tag/html.ipp"
#include "thumbnail/html.ipp"
#include "user/html.ipp"
