%       Character
plural  Characters
is      entity
field   Allergy
    plural  Allergies
    type    string
field   Birth
    type    date
field   Death
    type    date
field   DeathCause
    name    Cause of Death
field   Ethnicity
    plural  Ethnicities
field   Eyes
field   eyecolor
    name    Eye Color
field   Fantasy
    plural  Fantasies
field   favcolor
    name    Favorite Color
field   Favorite
    plural  Favorites
field   Flaw
    plural  Flaws
field   Food
field   Gender
    plural  Genders
    value   Male
    value   Female
field   Hair
field   Height
field   Hobby
    plural  Hobbies
field   Hometown
field   Imperfection
field   Jewelry
field   Maiden
    name    Maiden Surname
field   nick
    name    Nickname
field   Occupation
field   Personality
field   Phobia
field   Politic
field   Religion
field   Skin
field   SkinColor
    name    Skin Color
field   Species
field   Temperament
field   Trait
field   Voice
field   Weight

