#!/usr/bin/python
import io, sys, os, os.path

sys.stdout = open(1, 'w', encoding='utf-8', closefd=False);

TLD = [
    # List taken from https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
    [ "ac", "Ascension Island", "Territory" ],
    [ "ad", "Andorra", "Nation" ],
    [ "ae", "United Arab Emirates", "Nation" ],
    [ "af", "Afghanistan", "Nation" ],
    [ "ag", "Antigua and Barbuda", "Nation" ],
    [ "ai", "Anguilla", "Territory" ],
    [ "al", "Albania", "Nation" ],
    [ "am", "Armenia", "Nation" ],
    [ "ao", "Angola", "Nation" ],
    [ "aq", "Antarctica", "Territory" ],
    [ "ar", "Argentina", "Nation" ],
    [ "as", "American Samoa", "Territory" ],
    [ "at", "Austria", "Nation" ],
    [ "au", "Australia", "Nation" ],
    [ "aw", "Aruba", "Nation" ],
    [ "ax", "Åland", "Nation" ],
    [ "az", "Azerbaijan", "Nation" ],
    [ "ba", "Bosnia and Herzegovina", "Nation" ],
    [ "bb", "Barbados", "Nation" ],
    [ "bd", "Bangladesh", "Nation"],
    [ "be", "Belgium", "Nation" ],
    [ "bf", "Burkina Faso", "Nation" ],
    [ "bg", "Bulgaria", "Nation" ],
    [ "bh", "Bahrain", "Nation" ],
    [ "bi", "Burundi", "Nation" ],
    [ "bj", "Benin", "Nation" ],
    [ "bm", "Bermuda", "Territory" ],
    [ "bn", "Brunei", "Nation" ],
    [ "bo", "Bolivia", "Nation" ],
    [ "bq", "Caribbean Netherlands", "Territory" ],
    [ "br", "Brazil", "Nation" ],
    [ "bs", "Bahamas", "Nation" ],
    [ "bt", "Bhutan", "Nation" ],
    [ "bw", "Botswana", "Nation" ],
    [ "by", "Belarus", "Nation" ],
    [ "bz", "Belize", "Nation" ],
    [ "ca", "Canada", "Nation" ],
    [ 'ca/ab', 'Alberta', 'Province' ],
    [ 'ca/bc', 'British Columbia', 'Province' ],
    [ 'ca/mb', 'Manitoba', 'Province' ],
    [ 'ca/nb', 'New Brunswick', 'Province' ],
    [ 'ca/nl', 'Newfoundland', 'Province' ],
    [ 'ca/ns', 'Nova Scotia', 'Province' ],
    [ 'ca/nt', 'Northwest Territories', 'Territory' ],
    [ 'ca/nu', 'Nunavut', 'Territory' ],
    [ 'ca/on', 'Ontario', 'Province' ],
    [ 'ca/pe', 'Prince Edward Island', 'Province' ],
    [ 'ca/qc', 'Quebec', 'Province' ],
    [ 'ca/sk', 'Saskatchewan', 'Province' ],
    [ 'ca/yt', 'Yukon', 'Territory' ],
    [ "cc", "Cocos Islands (AU)", "Territory" ],
    [ "cd", "Democratic Republic of the Congo", "Nation" ],
    [ "cf", "Central African Republic", "Nation" ],
    [ "cg", "Republic of the Congo", "Nation" ],
    [ "ch", "Switzerland", "Nation" ],
    [ "ci", "Ivory Coast", "Nation" ],
    [ "ck", "Cook Islands", "Nation" ],
    [ "cl", "Chile", "Nation" ],
    [ "cm", "Cameroon", "Nation" ],
    [ "cn", "China", "Nation" ],
    [ "co", "Colombia", "Nation" ],
    [ "cr", "Costa Rica", "Nation" ],
    [ "cu", "Cuba", "Nation" ],
    [ "cv", "Cape Verde", "Nation" ],
    [ "cw", "Curaçao", "Nation" ],
    [ "cx", "Christmas Island", "Territory" ],
    [ "cy", "Cyprus", "Nation" ],
    [ "cz", "Czech Republic", "Nation" ],
    [ "de", "Germany", "Nation" ],
    [ "dj", "Djibouti", "Nation" ],
    [ "dk", "Denmark", "Nation" ],
    [ "dm", "Dominica", "Nation" ],
    [ "do", "Domnican Republic", "Nation" ],
    [ "dz", "Algeria", "Nation" ],
    [ "ec", "Ecuador", "Nation" ],
    [ "ee", "Estonia", "Nation" ],
    [ "eg", "Egypt", "Nation" ],
    [ "eh", "Western Sahara", "Nation" ],
    [ "er", "Eritrea", "Nation" ],
    [ "es", "Spain", "Nation" ],
    [ "et", "Ethiopia", "Nation" ],
    [ "eu", "European Union", "Nation" ],
    [ "fi", "Finland", 'Nation' ],
    [ 'fj', 'Fiji', 'Nation' ],
    [ 'fk', 'Falkland Islands', 'Territory' ],
    [ 'fm', 'Micronesia', 'Nation' ],
    [ 'fo', 'Faroe Islands', 'Nation' ],
    [ 'fr', 'France', 'Nation' ],
    [ 'ga', 'Gabon', 'Nation' ],
    [ 'gd', 'Grenada', 'Nation' ],
    [ 'ge', 'Georgia', 'Nation' ],
    [ 'gf', 'French Guiana', 'Territory' ],
    [ 'gg', 'Guernsey', 'Territory' ],
    [ 'gh', 'Ghana', 'Nation' ],
    [ 'gi', 'Gibraltar', 'Territory' ],
    [ 'gl', 'Greenland', 'Territory' ],
    [ 'gm', 'Gambia', 'Nation' ],
    [ 'gn', 'Guinea', 'Nation' ],
    [ 'gp', 'Guadeloupe', 'Territory' ],
    [ 'gq', 'Equatorial Guinea', 'Nation' ],
    [ 'gr', 'Greece', 'Nation' ],
    [ 'gs', 'South Georgia', 'Territory' ],
    [ 'gt', 'Guatemala', 'Nation' ],
    [ 'gu', 'Guam', 'Territory'],
    [ 'gw', 'Guinea-Bissau', 'Nation'],
    [ 'gy', 'Guyana', 'Nation' ],
    [ 'hk', 'Hong Kong', "Territory" ],
    [ 'hm', 'Heard Island', 'Territory' ],
    [ 'hn', 'Honduras', 'Nation' ],
    [ 'hr', 'Croatia', 'Nation' ],
    [ 'ht', 'Haiti', 'Nation' ],
    [ 'hu', 'Hungary', 'Nation' ],
    [ 'id', 'Indonesia', 'Nation' ],
    [ 'ie', 'Ireland', 'Nation' ],
    [ 'il', 'Israel', 'Nation' ],
    [ 'im', "Isle of Man", "Territory" ],
    [ 'in', "India", 'Nation' ],
    [ 'io', 'British Indian Ocean', 'Territory' ],
    [ 'iq', 'Iraq', 'Nation' ],
    [ 'ir', 'Iran', 'Nation' ],
    [ 'it', 'Italy', 'Nation' ],
    [ 'je', 'Jersey', 'Territory' ],
    [ 'jm', 'Jamaica', 'Nation' ],
    [ 'jo', 'Jordan', 'Nation' ],
    [ 'jp', 'Japan', 'Nation' ],
    [ 'ke', 'Kenya', 'Nation' ],
    [ 'kg', 'Kyrgyzstan', 'Nation' ],
    [ 'kh', 'Cambodia', 'Nation' ],
    [ 'ki', 'Kiribati', 'Nation' ],
    [ 'km', 'Comoros', 'Nation' ],
    [ 'kn', 'St. Kitts and Nevis', 'Nation' ],
    [ 'kp', 'North Korea', 'Nation' ],
    [ 'kr', 'South Korea', 'Nation' ],
    [ 'kw', 'Kuwait', 'Nation' ],
    [ 'ky', 'Cayman Islands', 'Nation' ],
    [ 'kz', 'Kazakhstan', 'Nation' ],
    [ 'la', 'Laos', 'Nation' ],
    [ 'lb', 'Lebanon', 'Nation' ],
    [ 'lc', 'Saint Lucia', 'Nation' ],
    [ 'li', 'Liechtenstein', 'Nation' ],
    [ 'lk', 'Sri Lanka', 'Nation' ],
    [ 'lr', 'Liberia', 'Nation' ],
    [ 'ls', 'Lesotho', 'Nation' ],
    [ 'lt', 'Lithuania', 'Nation' ],
    [ 'lu', 'Luxembourg', 'Nation' ],
    [ 'lv', 'Latvia', 'Nation' ],
    [ 'ly', 'Libya', 'Nation' ],
    [ 'ma', 'Morocco', 'Nation' ],
    [ 'mc', 'Monaco', 'Nation' ],
    [ 'md', 'Moldova', 'Nation' ],
    [ 'me', 'Montenegro', 'Nation' ],
    [ 'mg', 'Madagascar', 'Nation' ],
    [ 'mh', 'Marshall Islands', 'Nation' ],
    [ 'mk', 'North Macedonia', 'Nation' ],
    [ 'ml', 'Mali', 'Nation' ],
    [ 'mm', 'Myanmar', 'Nation' ],
    [ 'mn', 'Mongolia', 'Nation' ],
    [ 'mo', 'Macau', 'Territory' ],
    [ 'mp', 'Northern Mariana Islands', 'Territory' ],
    [ 'mq', 'Martinique', 'Territory' ],
    [ 'mr', 'Mauritania', 'Nation' ],
    [ 'ms', 'Montserrat', 'Territory' ],
    [ 'mt', 'Malta', 'Nation' ],
    [ 'mu', 'Mauritius', 'Nation' ],
    [ 'mv', 'Maldives', 'Nation' ],
    [ 'mw', 'Malawi', 'Nation' ],
    [ 'my', 'Malaysia', 'Nation' ],
    [ 'mz', 'Mozambique', 'Nation' ],
    [ 'na', 'Namibia', 'Nation' ],
    [ 'nc', 'New Caledonia', 'Territory' ],
    [ 'ne', 'Niger', 'Nation' ],
    [ 'nf', 'Norfolk Island', 'Territory' ],
    [ 'ng', 'Nigeria', 'Nation' ],
    [ 'ni', 'Nicaragua', 'Nation' ],
    [ 'nl', 'Netherlands', 'Nation' ],
    [ 'no', 'Norway', 'Nation' ],
    [ 'np', 'Nepal', 'Nation' ],
    [ 'nr', 'Nauru', 'Nation' ],
    [ 'nu', 'Niue', 'Territory' ],
    [ 'nz', 'New Zealand', 'Nation' ],
    [ 'om', 'Oman', 'Nation' ],
    [ 'pa', 'Panama', 'Nation' ],
    [ 'pe', 'Peru', 'Nation' ],
    [ 'pf', 'French Polynesia', 'Territory' ],
    [ 'pg', 'Papua New Guinea', 'Nation' ],
    [ 'ph', 'Philipines', 'Nation' ],
    [ 'pk', 'Pakistan', 'Nation' ],
    [ 'pl', 'Poland', 'Nation' ],
    [ 'pm', 'St. Pierre and Miquelon', 'Territory' ],
    [ 'pn', 'Pitcairn Islands', 'Territory' ],
    [ 'pr', 'Puerto Rico', 'Territory' ],
    [ 'ps', 'Palestine', 'Territory' ],
    [ 'pt', 'Portugal', 'Nation' ],
    [ 'pw', 'Palau', 'Nation' ],
    [ 'py', 'Paraguay', 'Nation' ],
    [ 'qa', 'Qatar', 'Nation' ],
    [ 're', 'Réunion', 'Territory' ],
    [ 'ro', 'Romania', 'Nation' ],
    [ 'rs', 'Serbia', 'Nation' ],
    [ 'ru', 'Russia', 'Nation' ],
    [ 'rw', 'Rwanda', 'Nation' ],
    [ 'sa', 'Saudia Arabia', 'Nation' ],
    [ 'sb', 'Solomon Islands', 'Nation' ],
    [ 'sc', 'Seychelles', 'Nation' ],
    [ 'sd', 'Sudan', 'Nation' ],
    [ 'se', 'Sweden', 'Nation' ],
    [ 'sg', 'Singapore', 'Nation' ],
    [ 'sh', 'Saint Helena', 'Territory' ],
    [ 'si', 'Slovenia', 'Nation' ],
    [ 'sk', 'Slovakia', 'Nation' ],
    [ 'sl', 'Sierra Leone', 'Nation' ],
    [ 'sm', 'San Marino', 'Nation' ],
    [ 'sn', 'Senegal', 'Nation' ],
    [ 'so', 'Somalia', 'Nation' ],
    [ 'sr', 'Suriname', 'Nation' ],
    [ 'ss', 'South Sudan', 'Nation' ],
    [ 'st', 'São Tomé and Príncipe', 'Nation' ],
    [ 'su', 'Soviet Union', 'Nation' ],
    [ 'sv', 'El Salvador', 'Nation' ],
    [ 'sx', 'Sint Maarten', 'Territory' ],
    [ 'sy', 'Syria', 'Nation' ],
    [ 'sz', 'Eswatini', 'Nation' ],
    [ 'tc', 'Turks and Caicos Islands', 'Territory' ],
    [ 'td', 'Chad', 'Nation' ],
    [ 'tf', 'French Southern and Artarctic Lands', 'Territory' ],
    [ 'tg', 'Togo', 'Nation' ],
    [ 'th', 'Thailand', 'Nation' ],
    [ 'tj', 'Tajikistan', 'Nation' ],
    [ 'tk', 'Tokelau', 'Territory' ],
    [ 'tl', 'East Timor', 'Nation' ],
    [ 'tm', 'Turkmenistan', 'Nation' ],
    [ 'tn', 'Tunisia', 'Nation' ],
    [ 'to', 'Tonga', 'Nation' ],
    [ 'tr', 'Turkey', 'Nation' ],
    [ 'tt', 'Trinidad and Tobago', 'Nation' ],
    [ 'tv', 'Tuvalu', 'Nation' ],
    [ 'tw', 'Taiwan', 'Nation' ],
    [ 'tz', 'Tanzania', 'Nation' ],
    [ 'ua', 'Ukraine', 'Nation' ],
    [ 'ug', 'Uganda', 'Nation' ],
    [ 'uk', 'United Kingdom', 'Nation' ],
    [ 'us', 'United States', 'Nation' ],
    [ 'us/al', 'Alabama', 'USState' ],
    [ 'us/ak', 'Alaska', 'USState' ],
    [ 'us/ar', 'Arkansa', 'USState' ],
    [ 'us/az', 'Arizona', 'USState' ],
    [ 'us/ca', 'California', 'USState' ],
    [ 'us/co', 'Colorado', 'USState' ],
    [ 'us/ct', 'Connecticut', 'USState' ],
    [ 'us/ct', 'District of Columbia', 'Territory' ],
    [ 'us/de', 'Delaware', 'USState' ],
    [ 'us/fl', 'Florida', 'USState' ],
    [ 'us/ga', 'Georgia', 'USState' ],
    [ 'us/hi', 'Hawaii', 'USState' ],
    [ 'us/ia', 'Iowa', 'USState' ],
    [ 'us/id', 'Idaho', 'USState' ],
    [ 'us/il', 'Illinois', 'USState' ],
    [ 'us/in', 'Indiana', 'USState' ],
    [ 'us/ks', 'Kansas', 'USState' ],
    [ 'us/ky', 'Kentucky', 'USState' ],
    [ 'us/la', 'Louisana', 'USState' ],
    [ 'us/ma', 'Massachusetts', 'USState' ],
    [ 'us/md', 'Maryland', 'USState' ],
    [ 'us/me', 'Maine', 'USState' ],
    [ 'us/mi', 'Michigan', 'USState' ],
    [ 'us/mn', 'Minnesota', 'USState' ],
    [ 'us/ms', 'Mississippi', 'USState' ],
    [ 'us/mo', 'Missouri', 'USState' ],
    [ 'us/mt', 'Montana', 'USState' ],
    [ 'us/nc', 'North Carolina', 'USState' ],
    [ 'us/nd', 'North Dakota', 'USState' ],
    [ 'us/ne', 'Nebraska', 'USState' ],
    [ 'us/nh', 'New Hampshire', 'USState' ],
    [ 'us/nj', 'New Jersey', 'USState' ],
    [ 'us/nm', 'New Mexico', 'USState' ],
    [ 'us/nv', 'Nevada', 'USState' ],
    [ 'us/ny', 'New York', 'USState' ],
    [ 'us/oh', 'Ohio', 'USState' ],
    [ 'us/ok', 'Oklahoma', 'USState' ],
    [ 'us/or', 'Oregon', 'USState' ],
    [ 'us/pa', 'Pennsylvania', 'USState' ],
    [ 'us/ri', 'Rhode Island', 'USState' ],
    [ 'us/sc', 'South Carolina', 'USState' ],
    [ 'us/sd', 'South Dakota', 'USState' ],
    [ 'us/tn', 'Tennessee', 'USState' ],
    [ 'us/tx', 'Texas', 'USState' ],
    [ 'us/ut', 'Utah', 'USState' ],
    [ 'us/vt', 'Vermont', 'USState' ],
    [ 'us/va', 'Virgina', 'USState' ],
    [ 'us/wa', 'Washington', 'USState' ],
    [ 'us/wi', 'Wisconsin', 'USState' ],
    [ 'us/wv', 'West Virginia', 'USState' ],
    [ 'us/wy', 'Wyoming', 'USState' ],
    [ 'uy', 'Uruguay', 'Nation' ],
    [ 'uz', 'Uzbekistan', 'Nation' ],
    [ 'va', 'Vatican City', 'Nation' ],
    [ 'vc', 'St Vincent and the Grenadines', 'Nation' ],
    [ 've', 'Venezuela', 'Nation' ],
    [ 'vg', 'British Virgin Islands', 'Territory' ],
    [ 'vi', 'United States Virgin Islands', 'Territory' ],
    [ 'vn', 'Vietnam', 'Nation' ],
    [ 'vu', 'Vanuatu', 'Nation' ],
    [ 'wf', 'Wallis and Futuna', 'Territory' ],
    [ 'ws', 'Samoa', 'Nation' ],
    [ 'ye', 'Yemen', 'Nation' ],
    [ 'yt', 'Mayotte', 'Territory' ],
    [ 'za', 'South Africa', 'Nation' ],
    [ 'zm', 'Zambia', 'Nation' ],
    [ 'zw', 'Zimbabwe', 'Nation' ]
]

ROOT = '../share/template/geo'


for tld in TLD:
    dir     = tld[0]
    name    = tld[1]
    type    = tld[2]
    
    full    = '%s/%s' % (ROOT, dir)
    leaf    = '%s/%s.y' % (ROOT, dir)
    os.makedirs(full, exist_ok=True)
    d           = dict();
    d['abbr']   = tld[0]
    d['name']   = name
    d['type']   = type
    
    if not os.path.exists(leaf):
        with open(leaf, 'w', encoding='utf8') as f:
            f.write("""<?xml version="1.0" encoding="UTF-8"?>
<yq_leaf>
    <title>%(name)s</title>
    <abbr>%(abbr)s</abbr>
    <class>place</class>
    <class>%(type)s</class>
    <attr key="name" id="1">%(name)s</attr>
    <context/>
</yq_leaf>""" % d)
        f.close()
    
    print("%s => %s" % (dir, name) )


